### ISSUE TITLE
Issue with "min"

### ISSUE THREAD

**Issue by gareth-ib** [andreivictor/select2-customSelectionAdapter#3]
First of, great plugin! Thanks for making it!
I found an issue where the "min" version has a problem where the search ability doesn't work when the selection is empty, but becomes searchable once an entry is selected. It works fine with the non-compressed version of the .js script in the same ( latest today ) package.
From looking at the DOM, the input object does not exist on load like it should. I'm not sure why this is happening, hopefully you can see easily. Thanks!

**Comment by andreivictor** [comment]
Thanks for your feedback!
It is my mistake, it seems that I forgot to commit the minified versions after the last build.
Should be fixed now.
Thanks a lot!
